name: Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload files to cPanel via FTP
      uses: appleboy/ftp-action@v0.1.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        source: "public_html/*"  # Path to your local code in the GitHub repo
        target: "/public_html"  # Target directory on the server (cPanel public_html directory)
