name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: 162.0.215.195          # Replace with your Namecheap server's IP address
        username: benpohmq       # Replace with your SSH username (e.g., 'jackgkrl')
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "public_html/*"
        target: "/home/benpohmq/public_html"  # Replace with the correct target path
        port: 21098                     # Replace with your SSH port (default is usually 22, but Namecheap uses 21098)
